openapi: "3.0.0"
info:
  title: Customer Master Data Management
  version: 1.0.0
security:
  - keycloak: [ ]
paths:
  /customers:
    $ref: "customer.yaml#/paths/~1customers"
  /customers/{id}:
    $ref: "customer.yaml#/paths/~1customers~1{id}"

components:
  securitySchemes:
    keycloak:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost:8080/realms/acroteq/protocol/openid-connect/auth
          scopes: { }
