components:
  parameters:
    limitQueryParam:
      name: limit
      description: How many items to return at one time (max 100)
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 100
    idPathParam:
      name: id
      description: The id of the customer
      in: path
      required: true
      schema:
        type: integer
        format: int64
