databaseChangeLog:
  - changeSet:
      id: 1744296523753-1
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: credit_balancesPK
                  name: id
                  type: BIGINT
              - column:
                  name: created_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: created_timestamp
                  type: timestamp
              - column:
                  name: lasted_modified_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: last_modified_timestamp
                  type: timestamp
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: total_credit_amount
                  type: NUMBER(38, 2)
              - column:
                  constraints:
                    nullable: false
                  name: total_credit_currency_id
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: customer_id
                  type: BIGINT
            tableName: credit_balances
  - changeSet:
      id: 1744296523753-2
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: credit_changesPK
                  name: id
                  type: BIGINT
              - column:
                  name: created_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: created_timestamp
                  type: timestamp
              - column:
                  name: lasted_modified_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: last_modified_timestamp
                  type: timestamp
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: credit_change_event_type
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: credit_delta_amount
                  type: NUMBER(38, 2)
              - column:
                  constraints:
                    nullable: false
                  name: credit_delta_currency_id
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: transaction_type
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: customer_id
                  type: BIGINT
            tableName: credit_changes
  - changeSet:
      id: 1744296523753-3
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: customersPK
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_offset
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_partition
                  type: INT
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: credit_limit_amount
                  type: NUMBER(38, 2)
              - column:
                  constraints:
                    nullable: false
                  name: credit_limit_currency_id
                  type: VARCHAR(255)
            tableName: customers
  - changeSet:
      id: 1744296523753-4
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: paymentsPK
                  name: id
                  type: BIGINT
              - column:
                  name: created_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: created_timestamp
                  type: timestamp
              - column:
                  name: lasted_modified_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: last_modified_timestamp
                  type: timestamp
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: order_id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: order_version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: status
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: value_amount
                  type: NUMBER(38, 2)
              - column:
                  constraints:
                    nullable: false
                  name: value_currency_id
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: customer_id
                  type: BIGINT
            tableName: payments
  - changeSet:
      id: 1744296523753-5
      author: adamcc (generated)
      changes:
        - addUniqueConstraint:
            columnNames: customer_id
            constraintName: UC_CREDIT_BALANCESCUSTOMER_ID_COL
            tableName: credit_balances
  - changeSet:
      id: 1744296523753-6
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: customer_id
            baseTableName: payments
            constraintName: FK45dp0030s8e3myd8n6ky4e79g
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: customers
            validate: true
  - changeSet:
      id: 1744296523753-7
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: customer_id
            baseTableName: credit_changes
            constraintName: FKb8h58sx1m3as3krk0hd3l2k06
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: customers
            validate: true
  - changeSet:
      id: 1744296523753-8
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: customer_id
            baseTableName: credit_balances
            constraintName: FKtijd5rj2past4urdm86ekk621
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: customers
            validate: true
