openapi: "3.0.0"
info:
  title: Airline Master Data Management
  version: 1.0.0
security:
  - keycloak: [ ]
paths:
  /airlines:
    $ref: "airlines.yaml#/paths/~1airlines"
  /airlines/{airlineCode}:
    $ref: "airlines.yaml#/paths/~1airlines~1{airlineCode}"

  /airlines/{airlineCode}/flights:
    $ref: "flights.yaml#/paths/~1airlines~1{airlineCode}~1flights"
  /airlines/{airlineCode}/flights/{flightCode}:
    $ref: "flights.yaml#/paths/~1airlines~1{airlineCode}~1flights~1{flightCode}"

components:
  securitySchemes:
    keycloak:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost:8080/realms/acroteq/protocol/openid-connect/auth
          scopes: { }
