CREATE SCHEMA IF NOT EXISTS airline_approval;
CREATE SCHEMA IF NOT EXISTS airline_master;
CREATE SCHEMA IF NOT EXISTS customer_master;
CREATE SCHEMA IF NOT EXISTS orders;
CREATE SCHEMA IF NOT EXISTS payment;

ALTER USER POSTGRES PASSWORD NULL;