databaseChangeLog:
  - changeSet:
      id: 1744296524056-1
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: airlinesPK
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_offset
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_partition
                  type: INT
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: active
                  type: BOOLEAN
              - column:
                  constraints:
                    nullable: false
                  name: code
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: name
                  type: VARCHAR(255)
            tableName: airlines
  - changeSet:
      id: 1744296524056-2
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: customersPK
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_offset
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_partition
                  type: INT
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: first_name
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: last_name
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: user_name
                  type: VARCHAR(255)
            tableName: customers
  - changeSet:
      id: 1744296524056-3
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: flightsPK
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_offset
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_partition
                  type: INT
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: code
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: flight_price_amount
                  type: NUMBER(38, 2)
              - column:
                  constraints:
                    nullable: false
                  name: flight_price_currency_id
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: airline_id
                  type: BIGINT
            tableName: flights
  - changeSet:
      id: 1744296524056-4
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                  name: order_id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: failure_message
                  type: VARCHAR(255)
            tableName: order_failure_messages
  - changeSet:
      id: 1744296524056-5
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: order_itemsPK
                  name: id
                  type: BIGINT
              - column:
                  name: created_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: created_timestamp
                  type: timestamp
              - column:
                  name: lasted_modified_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: last_modified_timestamp
                  type: timestamp
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: quantity
                  type: INT
              - column:
                  constraints:
                    nullable: false
                  name: flight_id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: order_id
                  type: BIGINT
            tableName: order_items
  - changeSet:
      id: 1744296524056-6
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: ordersPK
                  name: id
                  type: BIGINT
              - column:
                  name: created_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: created_timestamp
                  type: timestamp
              - column:
                  name: lasted_modified_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: last_modified_timestamp
                  type: timestamp
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: city
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: postal_code
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: street
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: order_status
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: price_amount
                  type: NUMBER(38, 2)
              - column:
                  constraints:
                    nullable: false
                  name: price_currency_id
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: tracking_id
                  type: VARCHAR(36)
              - column:
                  constraints:
                    nullable: false
                  name: airline_id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: customer_id
                  type: BIGINT
            tableName: orders
  - changeSet:
      id: 1744296524056-7
      author: adamcc (generated)
      changes:
        - addUniqueConstraint:
            columnNames: code
            constraintName: UC_AIRLINESCODE_COL
            tableName: airlines
  - changeSet:
      id: 1744296524056-8
      author: adamcc (generated)
      changes:
        - addUniqueConstraint:
            columnNames: code
            constraintName: UC_FLIGHTSCODE_COL
            tableName: flights
  - changeSet:
      id: 1744296524056-9
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: order_id
            baseTableName: order_failure_messages
            constraintName: FK5vvs9mekc0mj6p5pjge87ewqi
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: orders
            validate: true
  - changeSet:
      id: 1744296524056-10
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: flight_id
            baseTableName: order_items
            constraintName: FK7ckqr1fyr5n8cayr87pdm7h8j
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: flights
            validate: true
  - changeSet:
      id: 1744296524056-11
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: order_id
            baseTableName: order_items
            constraintName: FKbioxgbv59vetrxe0ejfubep1w
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: orders
            validate: true
  - changeSet:
      id: 1744296524056-12
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: airline_id
            baseTableName: orders
            constraintName: FKf63129gwastf9wejt1rxigy0t
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: airlines
            validate: true
  - changeSet:
      id: 1744296524056-13
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: airline_id
            baseTableName: flights
            constraintName: FKieor4j3ivp3xu584qenhfh0gd
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: airlines
            validate: true
  - changeSet:
      id: 1744296524056-14
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: customer_id
            baseTableName: orders
            constraintName: FKpxtb8awmi0dk6smoh2vp1litg
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: customers
            validate: true
