databaseChangeLog:
  - changeSet:
      id: 1744375311423-1
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: airlinesPK
                  name: id
                  type: BIGINT
              - column:
                  name: created_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: created_timestamp
                  type: timestamp
              - column:
                  name: lasted_modified_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: last_modified_timestamp
                  type: timestamp
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: active
                  type: BOOLEAN
              - column:
                  constraints:
                    nullable: false
                  name: code
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: name
                  type: VARCHAR(255)
            tableName: airlines
  - changeSet:
      id: 1744375311423-2
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: flightsPK
                  name: id
                  type: BIGINT
              - column:
                  name: created_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: created_timestamp
                  type: timestamp
              - column:
                  name: lasted_modified_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: last_modified_timestamp
                  type: timestamp
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: available
                  type: BOOLEAN
              - column:
                  constraints:
                    nullable: false
                  name: code
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: price_amount
                  type: NUMBER(38, 2)
              - column:
                  constraints:
                    nullable: false
                  name: price_currency_id
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: airline_id
                  type: BIGINT
            tableName: flights
  - changeSet:
      id: 1744375311423-3
      author: adamcc (generated)
      changes:
        - addUniqueConstraint:
            columnNames: code
            constraintName: UC_AIRLINESCODE_COL
            tableName: airlines
  - changeSet:
      id: 1744375311423-4
      author: adamcc (generated)
      changes:
        - addUniqueConstraint:
            columnNames: code
            constraintName: UC_FLIGHTSCODE_COL
            tableName: flights
  - changeSet:
      id: 1744375311423-5
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: airline_id
            baseTableName: flights
            constraintName: FKieor4j3ivp3xu584qenhfh0gd
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: airlines
            validate: true
