databaseChangeLog:
  - changeSet:
      id: 1746803286664-1
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: airlinesPK
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_offset
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_partition
                  type: INT
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: active
                  type: BOOLEAN
              - column:
                  constraints:
                    nullable: false
                  name: code
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: name
                  type: VARCHAR(255)
            tableName: airlines
  - changeSet:
      id: 1746803286664-2
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: flightsPK
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_offset
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: kafka_partition
                  type: INT
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: available
                  type: BOOLEAN
              - column:
                  constraints:
                    nullable: false
                  name: code
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: price_amount
                  type: NUMBER(38, 2)
              - column:
                  constraints:
                    nullable: false
                  name: price_currency_id
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: airline_id
                  type: BIGINT
            tableName: flights
  - changeSet:
      id: 1746803286664-3
      author: adamcc (generated)
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: order_approvalsPK
                  name: id
                  type: BIGINT
              - column:
                  name: created_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: created_timestamp
                  type: timestamp
              - column:
                  name: lasted_modified_by
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: last_modified_timestamp
                  type: timestamp
              - column:
                  constraints:
                    nullable: false
                  name: version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: order_id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: order_version
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: status
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: airline_id
                  type: BIGINT
            tableName: order_approvals
  - changeSet:
      id: 1746803286664-4
      author: adamcc (generated)
      changes:
        - addUniqueConstraint:
            columnNames: code
            constraintName: UC_AIRLINESCODE_COL
            tableName: airlines
  - changeSet:
      id: 1746803286664-5
      author: adamcc (generated)
      changes:
        - addUniqueConstraint:
            columnNames: code
            constraintName: UC_FLIGHTSCODE_COL
            tableName: flights
  - changeSet:
      id: 1746803286664-6
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: airline_id
            baseTableName: order_approvals
            constraintName: FKd2l6lpk3hs7kcn3qqoenrnu5q
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: airlines
            validate: true
  - changeSet:
      id: 1746803286664-7
      author: adamcc (generated)
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: airline_id
            baseTableName: flights
            constraintName: FKieor4j3ivp3xu584qenhfh0gd
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: airlines
            validate: true
