package com.acroteq.food.ordering.system.common.application.exception.handler;

import jakarta.annotation.Nullable;
import lombok.Builder;
import lombok.NonNull;
import lombok.Value;

import java.util.List;

/**
 * This is a hand-implemented version of the Problem class that would normally be generated by openapi.  There's no
 * openapi interface here to generate, and we need this to set up the centralised generic error handling that will be
 * used by our Spring microservices that expose REST APIs.
 */
@Builder
@Value
public class Problem {

  @NonNull Integer code;

  @NonNull String reason;

  @NonNull String message;

  @Nullable String i18nCode;

  @Nullable List<String> i18nParameters;
}
