server:
  port: 8181

order-service:
  permit-cross-origin-from: http://localhost:8281
  payment:
    consumer-group-id: payment-consumer-group
    request-topic-name: payment-request
    response-topic-name: payment-response
  airline-approval:
    consumer-group-id: airline-approval-consumer-group
    request-topic-name: airline-approval-request
    response-topic-name: airline-approval-response
  airline-event:
    consumer-group-id: airline-event-consumer-group
    topic-name: airline-event
  customer-event:
    consumer-group-id: customer-event-consumer-group
    topic-name: customer-event

security:
  jwt:
    authority-prefix: SCOPE_
    principal-claim-name: "preferred_username"

spring:
  config:
    import: optional:file:.env[.properties]
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      default_schema: orders
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}?currentSchema=orders&binaryTransfer=true&reWriteBatchedInserts=true&stringType=unspecified
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: always
  liquibase:
    change-log: "classpath:db/changelog/changelog-master.yaml"
    default-schema: orders
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ticketing
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/acroteq/protocol/openid-connect/auth
            jwk-set-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/acroteq/protocol/openid-connect/certs
            token-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/acroteq/protocol/openid-connect/token
            user-info-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/acroteq/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/acroteq/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    security:
      protocol: "SSL"
    ssl:
      key-store-location: classpath:/certs/order-service.keystore.jks
      key-store-password: acroteq
      trust-store-location: classpath:/certs/order-service.truststore.jks
      trust-store-password: acroteq
    producer:
      acks: all
      batch-size: 16384
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      compression-type: snappy
      retries: 5
      properties:
        linger.ms: 5
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
        ssl.endpoint.identification.algorithm: ""
    listener:
      type: batch
      ack-mode: batch
      concurrency: 1
      poll-timeout: 150
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      heartbeat-interval: 3000
      max-poll-records: 500
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
        specific.avro.reader: true
        session.timeout.ms: 60000
        max.poll.interval.ms: 10000
        max.partition.fetch.bytes: 1048576
        max.poll.records: 10
        ssl.endpoint.identification.algorithm: ""

kafka:
  consumer:
    dead-letter:
      suffix: -dlt
    backoff:
      max-retries: 3
      initial-interval-in-seconds: 10
      multiplier: 2
      max-interval-in-seconds: 40
