openapi: "3.0.0"
info:
  title: Order Service
  version: 1.0.0
security:
  - keycloak: [ ]
paths:
  /orders:
    $ref: "orders.yaml#/paths/~1orders"
  /orders/{trackingId}:
    $ref: "orders.yaml#/paths/~1orders~1{trackingId}"

components:
  securitySchemes:
    keycloak:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost:8080/realms/acroteq/protocol/openid-connect/auth
          scopes: { }
