openapi: "3.0.0"
info:
  title: Order Service
  version: 1.0.0
security:
  - keycloak: [ ]
paths:
  /orders:
    get:
      summary: List all orders
      operationId: listOrders
      tags:
        - orders
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        '200':
          description: An  array of orders
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Orders"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
    post:
      summary: Create an order
      operationId: createOrder
      tags:
        - orders
      requestBody:
        description: The order to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderCommand"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateOrderResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"

  /orders/{trackingId}:
    get:
      summary: Info for a specific order
      operationId: getOrderByTrackingId
      tags:
        - orders
      parameters:
        - name: trackingId
          in: path
          required: true
          description: The tracking id of the order to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
components:
  securitySchemes:
    keycloak:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost:8080/realms/acroteq/protocol/openid-connect/auth
          scopes: { }

  schemas:
    CreateOrderCommand:
      type: object
      required:
        - customerId
        - airlineId
        - items
        - address
      properties:
        customerId:
          type: integer
          format: int64
        airlineId:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: "#/components/schemas/CreateOrderItemCommand"
        address:
          $ref: "#/components/schemas/CreateAddressCommand"

    CreateOrderResponse:
      type: object
      required:
        - id
        - trackingId
        - audit
        - status
        - message
      properties:
        id:
          type: integer
          format: int64
        trackingId:
          type: string
          format: uuid
        audit:
          $ref: "#/components/schemas/Audit"
        status:
          $ref: "#/components/schemas/OrderStatus"
        message:
          type: string
          maxLength: 50

    Order:
      type: object
      required:
        - id
        - trackingId
        - audit
        - status
        - customerId
        - airlineId
        - items
        - address
      properties:
        trackingId:
          type: string
          format: uuid
          readOnly: true
        audit:
          $ref: "#/components/schemas/Audit"
        status:
          $ref: "#/components/schemas/OrderStatus"
        id:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
          readOnly: true
        airlineId:
          type: integer
          format: int64
          readOnly: true
        items:
          type: array
          readOnly: true
          items:
            $ref: "#/components/schemas/OrderItem"
        address:
          $ref: "#/components/schemas/Address"

    OrderStatus:
      type: string
      enum: [ PENDING, PAID, APPROVED, CANCELLING, CANCELLED ]
      readOnly: true

    Orders:
      type: array
      maxItems: 100
      readOnly: true
      items:
        $ref: "#/components/schemas/Order"

    CreateOrderItemCommand:
      type: object
      required:
        - flightId
        - quantity
      properties:
        flightId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
          minimum: 1

    OrderItem:
      type: object
      required:
        - flightId
        - quantity
      properties:
        flightId:
          type: integer
          format: int64
          readOnly: true
        quantity:
          type: integer
          format: int32
          minimum: 1
          readOnly: true

    CreateAddressCommand:
      type: object
      required:
        - street
        - postalCode
        - city
      properties:
        street:
          type: string
          maxLength: 50
        postalCode:
          type: string
          maxLength: 10
        city:
          type: string
          maxLength: 50

    Address:
      type: object
      required:
        - street
        - postalCode
        - city
      properties:
        street:
          type: string
          maxLength: 50
          readOnly: true
        postalCode:
          type: string
          maxLength: 10
          readOnly: true
        city:
          type: string
          maxLength: 50
          readOnly: true

    Audit:
      type: object
      required:
        - createdTimestamp
        - lastModifiedTimestamp
      properties:
        createdTimestamp:
          type: string
          format: date-time
          readOnly: true
        lastModifiedTimestamp:
          type: string
          format: date-time
          readOnly: true

    Problem:
      type: object
      required:
        - code
        - reason
        - i18nCode
        - i18nParameters
        - message
      properties:
        code:
          type: integer
          format: int32
          readOnly: true
        reason:
          type: string
          maxLength: 50
          readOnly: true
        i18nCode:
          type: string
          readOnly: true
        i18nParameters:
          type: array
          readOnly: true
          items:
            type: string
            maxLength: 50
            readOnly: true
        message:
          type: string
          maxLength: 100
          readOnly: true
