server:
  port: 8183


airline-service:
  swagger-port: 8283
  airline-event:
    topic-name: airline-event

spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      default_schema: airline_master
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=airline_master&binaryTransfer=true&reWriteBatchedInserts=true&stringType=unspecified
    username: postgres
    password: ""
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: always
  liquibase:
    change-log: "classpath:db/changelog/changelog-master.yaml"
    default-schema: airline_master

kafka:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url: http://localhost:8081
  auto.register.schemas: false
  use.latest.version: true
  value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
  num-of-partitions: 3
  replication-factor: 3
  producer:
    acks: all
    batch-size: 16384
    batch-size-boost-factor: 100
    linger-ms: 5
    request-timeout-ms: 60000
    retry-count: 5
    serialisation:
      key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
      value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
      compression-type: snappy
